project:
  type: website
  output-dir: docs
lang: fr
  #resources: 
  #  - "*.css"
    
execute:
  freeze: true

website:
  title: "RomuAnalyst"
  site-url: https://romuanalyst.github.io/Website
  description: Website, portfolio, aide à l'apprentissage...
  repo-url: https://github.com/.............
  image: img/logo.png
  page-navigation: true
  reader-mode: true
  navbar:
    logo: img/tree.png
    title: "<span class='icon-line'></span>RomuAnalyst {{< fa solid person-walking >}}<span class='icon-line'></span>"
    right:
      - text: "{{< fa solid house-user >}}"
        href: index.qmd
      - text: Cours
        menu: 
          - text: "{{< fa brands r-project >}} et Posit"
            href: R et Posit.qmd
          - text: "Introduction à {{< fa brands r-project >}}"
            href: Introduction_R.qmd
          - text: "ggplot2"
            href: test2.qmd
          - text: "les fonctions"
            href: ia.qmd
          - text: "les boucles"
            href: ia2.qmd
          - text: "Shiny"
            href: Shiny.qmd 
      - text: Articles
        href: posts.qmd
      - text: Packages
        href: packages.qmd
      - text: Divers
        href: TP1.qmd
      - text: Bio
        href: presentation.qmd
      #- icon: github
      #  href: https://github.com/EllaKaye
      #- icon: twitter
      #  href: https://twitter.com/ellamkaye
  favicon: img/tree.png
  twitter-card: 
    title: "RomuAnalyst"
    description: Mon site sur mes projets
    image: img/favicon.png
    image-alt: |
      L'arbre centralise ou donne accès à de multitude de résultats.
    image-width: 500
    image-height: 500
    card-style: summary # alternative summary_large_image
    creator: "@Romu"
    site: "@Romu"
  open-graph: 
    #description: The personal website of Ella Kaye
    image: images/logo.png
    image-alt: |
       L'arbre centralise ou donne accès à de multitude de résultats.
    image-width: 500
    image-height: 500
    locale: fr-FR

format:
  html:
    theme: 
      light: assets/ek-theme-light.scss
      dark: assets/ek-theme-dark.scss
    css: assets/ek-styles.css
    code-block-border-left: true
    highlight-style: 
      light: assets/ek-light.theme
      dark: assets/ek-dark.theme
    smooth-scroll: true
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/romuanalyst.github.io/Website/**'
editor: source

